### ISSUE TITLE
MySQL Compatibility 

### ISSUE THREAD

**Issue by chakany** [xtotdam/dynmap-assemble#3]
There should be MySQL Database Compatibilty because not everyone is using the dynmap tiles folder to store tiles. This would be extremely helpful if you added this function to the script. And would be even better if you added the ability to download tiles from MySQL databases across the web!

**Comment by xtotdam** [comment]
Hi @chak217 
I am not using MySQL with dynmap and have little experience with it
Your pull request will be welcome
Cheers

**Comment by xtotdam** [comment]
As for downloading tiles across web, there are already tools to download tiles from maps built upon `leaflet.js`
In my opinion they should be used to obtain local copy of tiles before assembly
